services:
  postgres:
    image: postgres:16
    container_name: alemeno_postgres
    environment:
      POSTGRES_USER: alemeno
      POSTGRES_PASSWORD: alemeno_pass
      POSTGRES_DB: transactions_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: alemeno_redis
    ports:
      - "6379:6379"

  api:
    build: ./app
    container_name: alemeno_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code
      - uploads_data:/code/uploads
    environment:
      DATABASE_URL: postgresql://alemeno:alemeno_pass@postgres:5432/transactions_db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  worker:
    build: ./app
    container_name: alemeno_worker
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - ./app:/code
      - uploads_data:/code/uploads
    environment:
      DATABASE_URL: postgresql://alemeno:alemeno_pass@postgres:5432/transactions_db
      REDIS_URL: redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  uploads_data: