"""add file_hash to jobs

Revision ID: 248aef3005ce
Revises: 1e8303cdcda3
Create Date: 2026-06-14 06:22:14.573060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248aef3005ce'
down_revision: Union[str, None] = '1e8303cdcda3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('file_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_jobs_file_hash'), 'jobs', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_file_hash'), table_name='jobs')
    op.drop_column('jobs', 'file_hash')
    # ### end Alembic commands ###
